# Generated by Django 5.1.4 on 2025-01-10 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news_post',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AddField(
            model_name='news_post',
            name='autor',
            field=models.CharField(default='Puskin', max_length=100, verbose_name='Пользователь'),
            preserve_default=False,
        ),
    ]
